"""empty message

Revision ID: 04379d4e99ec
Revises: 384950c510e0
Create Date: 2023-08-11 12:22:26.136503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04379d4e99ec'
down_revision = '384950c510e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_post', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_author_post_users'), 'users', ['author_post'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_author_post_users'), type_='foreignkey')
        batch_op.drop_column('author_post')

    # ### end Alembic commands ###
